FROM node:16-alpine as base

WORKDIR /app

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=client


FROM nginx:latest as production
WORKDIR /app

COPY --from=base /app/packages/client/dist/ /app/
COPY --from=base /app/packages/client/nginx.conf /etc/nginx/nginx.conf

EXPOSE 3000

CMD [ "nginx", "-g", "daemon off;" ]