FROM node:16-alpine as base

WORKDIR /app

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build --scope=server


FROM node:16-alpine as production
WORKDIR /app

COPY --from=base /app/packages/server/dist/ /app/
COPY --from=base /app/packages/server/package.json /app/package.json
RUN yarn install --production=true

EXPOSE 3001

CMD [ "node", "/app/index.js" ]